### ISSUE TITLE
return descriptors?

### ISSUE THREAD

**Issue by antithing** [lacie-life/SPSG-TRT#2]
Hi! and thank you for making this code available. i am trying to integrate it into a SLAM system based on ORBSLAM2, and I need to access the descriptors from the keypoints to store in a map. 

How can i do this using this code?

Thanks!

**Comment by lacie-life** [comment]
You can see more in SuperPoint class [here](https://github.com/lacie-life/SPSG-TRT/blob/11cdc510ccee0ba498c209fce69ecf46e0087abc/src/super_point.cpp#L301).

**Comment by antithing** [comment]
Thank you! Great these are 32 x 8bit = 256, right? the same as ORB descriptor?

**Comment by antithing** [comment]
So if I want to make a cv::Mat of descriptors to mirror what the cv orb compute does, I can run:

`sample_descriptors(keypoints_, output_desc, descriptors_, desc_feature_dim, desc_feature_map_h, desc_feature_map_w);
`
which gives me a:

` std::vector<std::vector<double>> descriptors_;
`

Can i then turn this into a cv::mat?

Thanks!

**Comment by lacie-life** [comment]
The descriptors are included in the features: 

`Eigen::Matrix<double, 259, Eigen::Dynamic> &features`

You can follow [that](https://github.com/lacie-life/SPSG-TRT/blob/11cdc510ccee0ba498c209fce69ecf46e0087abc/src/super_point.cpp#L335) to extract descriptor and keypoint. Then convert it to cv::Mat for matching

**Comment by antithing** [comment]
Hi, sorry one more question!

I see that the descriptor has 256 values, where ORB has 32. 

Does this mean that I can't use it directly with an ORB matcher? or is there a conversion possible?

I am doing this currently:

```
  //keypoints and desc to cv format
    std::vector<cv::KeyPoint> kpnts;
    cv::Mat desc = cv::Mat(descriptors_.size(),256, CV_8U);

    for (int i = 1; i < 3; ++i) {
        for (int j = 0; j < keypoints_.size(); ++j) {
            features(i, j) = keypoints_[j][i-1];
            kpnts.push_back(cv::KeyPoint(cv::Point2f(keypoints_[j][i - 1]), 1));
        }
    }
    for (int m = 3; m < 259; ++m) {
        for (int n = 0; n < descriptors_.size(); ++n) {
            features(m, n) = descriptors_[n][m-3];
            desc.at<int>(m,n) = descriptors_[n][m - 3];
        }
    }
```

**Comment by lacie-life** [comment]
You can see in ORBMatcher class in ORB_SLAM2 origin source. The function to calculate the distance between descriptors [here](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/ORBmatcher.cc#L1647):

`// Bit set count operation from
// http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetParallel
int ORBmatcher::DescriptorDistance(const cv::Mat &a, const cv::Mat &b)
{
    const int *pa = a.ptr<int32_t>();
    const int *pb = b.ptr<int32_t>();

    int dist=0;

    for(int i=0; i<8; i++, pa++, pb++)
    {
        unsigned  int v = *pa ^ *pb;
        v = v - ((v >> 1) & 0x55555555);
        v = (v & 0x33333333) + ((v >> 2) & 0x33333333);
        dist += (((v + (v >> 4)) & 0xF0F0F0F) * 0x1010101) >> 24;
    }

    return dist;
}`

It only checks bit, so if it has the same number of values, it can run or you can you an simple descriptor distance like NORM2 like [that](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/4bf56e209856f3eed4b186874b2ab7e4c3c0e82b/src/SPmatcher.cc#L1668). But you need to check about Image Pyramid Feature extraction of ORB_SLAM, ORB will be extract in multi level of Pyramid, if you extract like that, the latency will increase.
